version: '3.3'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    volumes:
      - ./data:/var/lib/postgresql/data

  golang:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./configs:/prod/configs
