port: "8000"

db:
  username: "postgres"
  password: "qwerty"
  host: "db"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
  migration_url: "file://pkg/schemas"
  db_source: "postgres://postgres:qwerty@db:5432/postgres?sslmode=disable"